name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install cfitsio
      run: sudo apt-get install libcfitsio-dev
    - name: make
      run: make
    - name: execute
      run: output/main
